name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        diffusers-version: ["0.14.0", "0.15.0", "0.15.1", "0.16.0", "0.16.1", "0.17.0", "0.17.1", "0.18.0", "0.18.1", "0.18.2"]
    steps:
      - uses: actions/checkout@v3
      - name: Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: diffusers ${{ matrix.diffusers-version }}
        run: |
          python -m pip install . diffusers==${{ matrix.diffusers-version }} pytest
          pytest tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          python -m pip install . pysen==0.10.5 isort==5.12.0 black==23.7.0 flake8==6.0.0 mypy==1.4.1
          pysen run lint
